server:
  servlet:
    context-path: /api/v1
  port : 8081

spring:
  application:
    name: consul-internal
  jpa:
    generate-ddl: true
  datasource:
    hikari:
      maximumPoolSize: 20
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        healthCheckPath: /api/v1/message/ping
        healthCheckInterval: 20s

---
spring:
  profiles: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
